check50:
  dependencies:
    - "jupyter"
    - "pandas"
    - "nbformat"
  files:
    - !exclude "*"
    - !require "module 2.ipynb"
    - !require "answers.py"
    - !require "micro-movielens/"
    - !require "mini-movielens/"
