check50:
  dependencies:
    - "jupyter>=1.0"
    - "pandas>=1.0"
    - "nbformat>=5"
    - "matplotlib>=3.2"
    - "scipy>=1.4"
    - "nbconvert==5.4.0"
    - "notebook==5.6.0"
    - "jupyter-client==5.2.3"
  files:
    - !exclude "*"
    - !require "module1.ipynb"
