check50:
  dependencies:
    - "nbconvert==6.0.7"
    - "notebook>=6.3"
    - "pandas>=1.0"
    - "nbformat>=5"
    - "matplotlib>=3.2"
    - "scipy>=1.4"
  files:
    - !exclude "*"
    - !require "module1.ipynb"
